version: '3'

services:
  orient-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/orient-pypy:7.0.0
    volumes:
      - ./orient:/opt/orient/orient
      - ./pyproject.toml:/opt/orient/pyproject.toml
      - ./README.md:/opt/orient/README.md
      - ./setup.py:/opt/orient/setup.py
      - ./tests:/opt/orient/tests
    entrypoint: pytest
