version: '3'

services:
  orient-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/orient-cpython:7.0.0-alpha
    volumes:
      - ./orient:/opt/orient/orient
      - ./pyproject.toml:/opt/orient/pyproject.toml
      - ./README.md:/opt/orient/README.md
      - ./setup.py:/opt/orient/setup.py
      - ./tests:/opt/orient/tests
    entrypoint: pytest
