version: '3'

services:
  orient-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/orient-cpython:0.9.5
    volumes:
      - ./orient/:/opt/orient/orient/
      - ./tests/:/opt/orient/tests/
      - ./README.md:/opt/orient/README.md
      - ./requirements.txt:/opt/orient/requirements.txt
      - ./requirements-tests.txt:/opt/orient/requirements-tests.txt
      - ./setup.py:/opt/orient/setup.py
      - ./pytest.ini:/opt/orient/pytest.ini
    entrypoint: pytest
