version: '3'

services:
  orient-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/orient-cpython:1.5.0-alpha
    volumes:
      - ./orient:/opt/orient/orient
      - ./pytest.ini:/opt/orient/pytest.ini
      - ./README.md:/opt/orient/README.md
      - ./requirements-tests.txt:/opt/orient/requirements-tests.txt
      - ./requirements.txt:/opt/orient/requirements.txt
      - ./setup.py:/opt/orient/setup.py
      - ./tests:/opt/orient/tests
    entrypoint: pytest
